CREATE DATABASE IF NOT EXISTS diretorio;

USE diretorio;

CREATE TABLE -- Cadastro / chave primaria definida
  IF NOT EXISTS `01_20_11` (
    grupo_de_perfil int,
    cod_setor int,
    descricao_setor VARCHAR(25),
    codigo_cliente bigint,
    razao_social VARCHAR(25),
    bairro VARCHAR(25),
    ordem VARCHAR(25),
    status_do_cliente VARCHAR(10),
    nome_fantasia VARCHAR(25),
    frequencia_visita VARCHAR(25),
    periodicidade VARCHAR(25),
    proxima_visita varchar(25),
    visita_original varchar(25),
    inicio_visita varchar(25),
    cnpj VARCHAR(25),
    inscricao_estadual VARCHAR(25),
    cod_estabelecimento bigint,
    nome_estabelecimento VARCHAR(25),
    cod_pagto int,
    descricao_pagto VARCHAR(25),
    serasa VARCHAR(10),
    observacao VARCHAR(25),
    contato VARCHAR(25),
    cnpj_2 VARCHAR(25),
    contato_2 VARCHAR(25),
    cnpj_3 VARCHAR(25),
    ordem_por_historico VARCHAR(25),
    dias_entrega VARCHAR(25),
    el_dorado VARCHAR(10),
    endereco VARCHAR(25),
    cidade VARCHAR(25),
    cod_segmento int,
    segmento VARCHAR(25),
    primary key (codigo_cliente)
  );

CREATE TABLE -- Cadastro / chave primaria definida 
  IF NOT EXISTS `01_11` (
    codigo bigint,
    descricao VARCHAR(25),
    pgv int,
    empresa VARCHAR(10),
    tipo_marca VARCHAR(25),
    linha_marca int,
    embalagem VARCHAR(25),
    marca int,
    vasilhame int,
    garrrafeira int,
    icms int,
    tipo_roadshow VARCHAR(10),
    peso_bruto_kg decimal(10, 4),
    fator int,
    fator_hecto float,
    fator_hecto_comercial float,
    ind_palmtop VARCHAR(10),
    grupo int,
    grupo_remuneracao int,
    ean bigint,
    tab_icms int,
    caixas_pallet int,
    nr_fator_conversao decimal(10, 2),
    lastro VARCHAR(25),
    fam_embalagem_siv int,
    pauta_pis_litro int,
    pauta_cofins_litro int,
    caixas_pallet_2 int,
    capacidade_2 int,
    fat_ajust_2 float,
    caixas_pallet_3 int,
    capacidade_3 int,
    fat_ajust_3 float,
    caixas_pallet_4 int,
    capacidade_4 int,
    fat_ajust_4 float,
    ordem_de_carga int,
    estoque_minimo_puxada int,
    codigo_produto_sap int,
    vasilhame_ficticio VARCHAR(25),
    ncm bigint,
    apura_royalties VARCHAR(10),
    tipo_produto_royalties int,
    cest bigint,
    ean_trib bigint,
    codigo_unitario int,
    descricao_unitaria VARCHAR(25),
    subtipo int,
    primary key (codigo)
  );

CREATE TABLE -- Mensal /  chave primaria definida
  IF NOT EXISTS `03_01_46_06` (
    id_pedido bigint,
    unb bigint,
    cliente bigint,
    razao_social VARCHAR(25),
    data_criacao varchar(25),
    hora_criacao time,
    data_entrega date,
    data_ultima_modificacao datetime,
    data_exclusao_cancelamento datetime,
    vendedor int,
    condicao_pagamento int,
    descricao_condicao_pagamento VARCHAR(25),
    indicador_fora_de_rota VARCHAR(10),
    status_exportacao_p VARCHAR(25),
    etapa_pedido VARCHAR(25),
    sem_estoque VARCHAR(25),
    taxa_fora_rota decimal(10, 2),
    codigo_pedido_promax varchar(25),
    data_geracao_arquivo_p DATETIME,
    status_critica VARCHAR(25),
    tipo_solicitacao VARCHAR(25),
    codigo_critica varchar(25),
    criticas_magento varchar(25),
    alcada_original VARCHAR(25),
    alcada_rejeicao VARCHAR(25),
    usuario_aprovador_1 VARCHAR(25),
    usuario_aprovador_2 VARCHAR(25),
    nota_fiscal VARCHAR(25),
    status_nota_fiscal VARCHAR(25),
    desconto_total DECIMAL(10, 2),
    valor_total_pedido decimal(10, 2),
    valor_total_nota_fiscal decimal(10, 2),
    origem_pedido VARCHAR(25),
    codigo_incremento_prazo varchar(25),
    motivo_cancelamento VARCHAR(100),
    taxa_adf_utilizada decimal(10, 2),
    taxa_adf_escalonada decimal(10, 2),
    valor_pedido_minimo decimal(10, 2),
    indicador_entrega_alternativa VARCHAR(25),
    importado_pelo_hercules VARCHAR(25),
    primary key (id_pedido)
  ) ROW_FORMAT = DYNAMIC;

CREATE TABLE -- Mensal / chave primaria definida
  IF NOT EXISTS `03_01_47_01` (
    id_linha int AUTO_INCREMENT primary key,
    cod_puxada int,
    nome_filial VARCHAR(50),
    geografia VARCHAR(50),
    canal_de_marcacao VARCHAR(20),
    origem VARCHAR(20),
    gerente_vendas int,
    nome_gerente_vendas VARCHAR(25),
    area int,
    nome_area VARCHAR(25),
    setor int,
    nome_setor VARCHAR(25),
    vendedor int,
    nome_vendedor VARCHAR(25),
    cliente int,
    nome_cliente VARCHAR(50),
    categoria_cliente int,
    desc_categoria_cliente VARCHAR(50),
    tipo_movimento int,
    desc_tipo_movimento VARCHAR(50),
    operacao int,
    desc_operacao VARCHAR(50),
    transportadora int,
    nome_transportadora VARCHAR(50),
    nr_roadshow int,
    data DATE,
    pedido int,
    nota_fiscal bigint,
    serie int,
    tipo_marca int,
    desc_tipo_marca VARCHAR(50),
    embalagem int,
    desc_embalagem VARCHAR(50),
    cod_prod int,
    nome_prod VARCHAR(50),
    volume_marcacao DECIMAL(10, 3),
    volume_entrega DECIMAL(10, 3),
    motivo VARCHAR(50),
    submotivo_1 VARCHAR(50),
    submotivo_2 VARCHAR(50),
    codigo_marca int,
    descricao_marca VARCHAR(50),
    cod_municipio VARCHAR(20),
    nome_municipio VARCHAR(50),
    cod_rede VARCHAR(20),
    nome_rede VARCHAR(50),
    fora_de_rota VARCHAR(10),
    ajuste VARCHAR(10),
    idade_do_pedido INT,
    situacao VARCHAR(20),
    prioridade_road VARCHAR(20),
    prioridade_venda VARCHAR(20),
    hora_envio_road_show DATETIME,
    hora_retorno_road_show DATETIME,
    pedido_origem VARCHAR(50),
    cod_filial_origem VARCHAR(20),
    nome_filial_origem VARCHAR(50),
    mapa int,
    pedido_quebra_original VARCHAR(50),
    pedido_cliente bigint,
    pedido_sistema_origem VARCHAR(25),
    data_entrega_nf varchar(25),
    entrega_real DATETIME,
    visita_otif VARCHAR(50),
    primeira_quebra VARCHAR(20),
    cliente_ponto_de_apoio VARCHAR(25),
    data_hora_envio_road_magali DATETIME,
    data_hora_retorno_road_magali DATETIME,
    codigo_condicao_de_pagamento int,
    descricao_condicao_de_pagamento VARCHAR(25),
    quantidade INT,
    unid_venda VARCHAR(10),
    unique key uk_tabela_03_01_47_01 (
      id_linha,
      pedido,
      cod_prod,
      volume_entrega,
      quantidade
    )
  ) ROW_FORMAT = DYNAMIC;

CREATE TABLE -- Mensal / chave primaria definida
  IF NOT EXISTS `03_02_24` (
    mapa bigint,
    data date,
    unb_nota VARCHAR(25),
    nota bigint,
    serie int,
    unb_cliente VARCHAR(25),
    cod_cliente int,
    nome_cliente VARCHAR(25),
    telefone VARCHAR(25),
    area int,
    setor int,
    placa VARCHAR(25),
    valor decimal(10, 2),
    volume decimal(10, 2),
    data_devol varchar(25),
    cod_motivo int,
    desc_motivo VARCHAR(25),
    orig_pedido VARCHAR(25),
    usuario VARCHAR(25),
    hora time,
    primary key (nota)
  );

CREATE TABLE -- Mensal / chave primaria definida
  IF NOT EXISTS `03_02_37_operacao_veiculo_mapa` (
    empresa int,
    filial int,
    operacao int,
    codigo_vei int,
    mapa int,
    dt_operacao varchar(25),
    emissao date,
    nota bigint,
    serie int,
    `status` VARCHAR(10),
    mot_cancelamento int,
    transf_multi_cdd VARCHAR(25),
    cliente int,
    nome VARCHAR(25),
    indicador_ca_prazo VARCHAR(25),
    produto int,
    unidade VARCHAR(10),
    descricao VARCHAR(25),
    combo_vendas VARCHAR(25),
    qtde int,
    valor decimal(10, 2),
    icms decimal(10, 2),
    icms_st decimal(10, 2),
    adic_finan decimal(10, 2),
    desconto decimal(10, 2),
    total decimal(10, 2),
    mapa_2 int,
    nr_tit_bco int,
    nr_pedido int,
    ipi decimal(10, 2),
    frete VARCHAR(25),
    adic_escal VARCHAR(25),
    trib_pis_pauta VARCHAR(25),
    trib_pis_aliquota VARCHAR(25),
    trib_cofins_pauta VARCHAR(25),
    trib_cofins_aliquota VARCHAR(25),
    nf_referencia VARCHAR(25),
    serie_nf_referencia VARCHAR(25),
    data_nf_referencia VARCHAR(25),
    status_nf_e VARCHAR(25),
    motivo_rejeicao_denegacao int,
    descricao_motivo VARCHAR(25),
    data_contingencia VARCHAR(25),
    hora_contingencia VARCHAR(25),
    nr_protocolo varchar(50),
    chave_de_acesso_nf_e VARCHAR(100),
    indicador_nf_e VARCHAR(10),
    hora_envio time,
    hora_retorno time,
    indicador_de_caneta VARCHAR(10),
    indicador_fora_rota_entrega VARCHAR(10),
    id_mensageria VARCHAR(10),
    status_sefaz_hb_nfe_x int,
    data_retorno_hb_nfe_x varchar(25),
    hora_retorno_hb_nfe_x time,
    data_envio_2_v VARCHAR(25),
    estoque_atualizado VARCHAR(10),
    dt_emissao_fiscal varchar(25),
    nota_fiscal_exportada_para_promax_central VARCHAR(25),
    prazo int,
    nf_retorno_vasilhame VARCHAR(25),
    nf_venda_ag_produto_material VARCHAR(25),
    nf_retorno_remessa_puxada_ag VARCHAR(25),
    nf_recolha_comodato VARCHAR(25),
    nf_troca_realizada VARCHAR(25),
    taxa_de_entrega decimal(10, 2),
    origem_do_pedido VARCHAR(25),
    vl_desconto_algoritmo VARCHAR(25),
    meta_algoritmo VARCHAR(25),
    desc_disponivel_padrao VARCHAR(25),
    desc_disponivel_acao VARCHAR(25),
    vl_desconto_algoritmo_aut VARCHAR(25),
    codigo_acao_desconto_alg_fix VARCHAR(25),
    valor_ttv_planejado decimal(10, 2),
    valor_sugerido VARCHAR(25),
    cod_setor_atendimento VARCHAR(25),
    tipo_setor_atendimento VARCHAR(25),
    setor int,
    codigo_da_escalonada_do_pedido VARCHAR(25),
    tipo_escalonada_do_pedido VARCHAR(25),
    faixa_da_escalonada_do_pedido int,
    indicador_de_preco_pontual VARCHAR(25),
    indicador_de_preco_cheio VARCHAR(25),
    ttv_da_escalonada_do_pedido VARCHAR(25),
    indicador_de_unidade VARCHAR(25),
    data_captura_pedido VARCHAR(25),
    nf_regerada int,
    serie_nf_regerada int,
    indicador_cancelamento VARCHAR(25),
    red_icms_proprio VARCHAR(25),
    red_fecop_proprio VARCHAR(25),
    red_icms_st VARCHAR(25),
    red_fecop_st VARCHAR(25),
    cod_situacao_tributaria VARCHAR(25),
    unnamed VARCHAR(10),
    id_linha int AUTO_INCREMENT,
    primary key (id_linha),
    unique key uk_operacao_veiculo_mapa (
      id_linha,
      mapa,
      nota,
      serie,
      produto,
      qtde,
      desconto
    )
  ) ROW_FORMAT = DYNAMIC;

CREATE TABLE -- Mensal / 
  IF NOT EXISTS `03_02_37_`

CREATE TABLE -- mensal 
  IF NOT EXISTS `roteirizador`(
    data_roteiro date,
    sessao int,	
    nome_sessao	varchar(10),
    exportado	varchar(10),
    numero_rota int,
    deposito	varchar(50),
    placa	varchar(25),
    nome	varchar(50),
    tipo_veiculo varchar(50),
    motorista	varchar(50),
    pedagio	decimal(10,4),
    custo_distancia	decimal(10,4),
    custo_quantidade_dias	decimal(10,4),
    custo_hora	decimal(10,4),
    custo_quantidade_atividades	decimal(10,4),
    custo_total	decimal(10,4),
    valor_total decimal(10,4),
    perc_custo decimal(10,4),
    capacidade_veiculo decimal(10,4),
    capacidade_utilizada decimal(10,4),
    perc_capacidade decimal(10,4),
    peso_veiculo decimal(10,4),
    peso_utilizado decimal(10,4),
    inicio_da_rota datetime,
    fim_da_rota datetime,
    perc_peso decimal(10,4),
    quantidade_entregas int,
    setores varchar(75),
    tempo_em_rota_hhmmss time,
    dias_em_rota int,
    distancia_km decimal(10,4),
    tempo_dirigindo_hhmmss time,
    tempo_atendimento_hhmmss time,
    data_exportado datetime,
    custo_fixo_da_rota decimal(10,4),
    custo_formula varchar(10),
    ponto_de_saida varchar(50),
    distancia_ida_ponto_de_apoio_km varchar(10) ,
    distancia_volta_ponto_de_apoio_km varchar(10),
    transportadora varchar(25),
    perc_ajuste_velocidade_modificado varchar(10),
    perc_ajuste_velocidade_original varchar(10),
    quantidade_pallets decimal(10,4),
    jornada varchar(10),
    total_de_itens decimal(10,4),
    prateleira varchar(10),
    codigo_unidade int,
    hectolitro_hl varchar(10),
    codigo_tipo_rota int,
    nome_tipo_rota varchar(25),
    perfil_recarga varchar(10),
    rota_otimizada varchar(10),
    justificativa_da_violacao varchar(50),
    filial_corporativa varchar(50),
    data_criacao_sessao datetime,
    modelo_de_entrega varchar(50),
    fuso_horario varchar(50),

    primary key (data_roteiro, sessao, numero_rota, placa)
  );
CREATE TABLE -- Mensal / chave primaria definida
  IF NOT EXISTS `03_02_37_tipo_movto` (
    empresa int,
    filial int,
    tipo_movto int,
    unnamed int,
    unnamed_1 int,
    dt_operacao varchar(25),
    emissao date,
    nota bigint,
    serie int,
    status VARCHAR(25),
    mot_cancelamento int,
    transf_multi_cdd VARCHAR(25),
    cliente int,
    nome VARCHAR(25),
    indicador_ca_prazo VARCHAR(25),
    produto int,
    unidade VARCHAR(10),
    descricao VARCHAR(25),
    combo_vendas VARCHAR(25),
    qtde int,
    valor decimal(10, 2),
    icms decimal(10, 2),
    icms_st decimal(10, 2),
    adic_finan decimal(10, 2),
    desconto decimal(10, 2),
    total decimal(10, 2),
    mapa int,
    nr_tit_bco int,
    nr_pedido VARCHAR(25),
    ipi VARCHAR(25),
    frete VARCHAR(25),
    adic_escal VARCHAR(25),
    trib_pis_pauta VARCHAR(25),
    trib_pis_aliquota VARCHAR(25),
    trib_cofins_pauta VARCHAR(25),
    trib_cofins_aliquota VARCHAR(25),
    nf_referencia int,
    serie_nf_referencia int,
    data_nf_referencia VARCHAR(25),
    status_nf_e VARCHAR(25),
    motivo_rejeicao_denegacao VARCHAR(25),
    descricao_motivo VARCHAR(25),
    data_contingencia VARCHAR(25),
    hora_contingencia VARCHAR(25),
    nr_protocolo VARCHAR(25),
    chave_de_acesso_nf_e VARCHAR(100),
    indicador_nf_e VARCHAR(25),
    hora_envio VARCHAR(25),
    hora_retorno VARCHAR(25),
    indicador_de_caneta VARCHAR(25),
    indicador_fora_rota_entrega VARCHAR(25),
    id_mensageria VARCHAR(25),
    status_sefaz_hb_nfe_x VARCHAR(25),
    data_retorno_hb_nfe_x VARCHAR(25),
    hora_retorno_hb_nfe_x VARCHAR(25),
    data_envio_2_v VARCHAR(25),
    estoque_atualizado VARCHAR(25),
    dt_emissao_fiscal VARCHAR(25),
    nota_fiscal_exportada_para_promax_central VARCHAR(25),
    prazo int,
    nf_retorno_vasilhame VARCHAR(25),
    nf_venda_ag_produto_material VARCHAR(25),
    nf_retorno_remessa_puxada_ag VARCHAR(25),
    nf_recolha_comodato VARCHAR(25),
    nf_troca_realizada VARCHAR(25),
    taxa_de_entrega decimal(10, 2),
    origem_do_pedido VARCHAR(25),
    vl_desconto_algoritmo VARCHAR(25),
    meta_algoritmo VARCHAR(25),
    desc_disponivel_padrao VARCHAR(25),
    desc_disponivel_acao VARCHAR(25),
    vl_desconto_algoritmo_aut VARCHAR(25),
    codigo_acao_desconto_alg_fix VARCHAR(25),
    valor_ttv_planejado VARCHAR(25),
    valor_sugerido VARCHAR(25),
    cod_setor_atendimento VARCHAR(25),
    tipo_setor_atendimento VARCHAR(25),
    data_captura_pedido VARCHAR(25),
    nf_regerada int,
    serie_nf_regerada int,
    indicador_cancelamento VARCHAR(25),
    red_icms_proprio VARCHAR(25),
    red_fecop_proprio VARCHAR(25),
    red_icms_st decimal(10, 2),
    red_fecop_st VARCHAR(25),
    unnamed_2 varchar(25),
    primary key (tipo_movto, nota, serie)
  ) ROW_FORMAT = DYNAMIC;

CREATE TABLE -- Mensal / chave primaria definida
  IF NOT EXISTS `03_05_30_cliente` (
    cod_cliente int,
    descricao VARCHAR(25),
    data date,
    mapa int,
    veiculo int,
    placa VARCHAR(25),
    motorista int,
    cod_produto INT,
    descricao_2 VARCHAR(25),
    cod_cliente_2 int,
    descricao_3 VARCHAR(25),
    peso int,
    perc_ocup int,
    volume decimal(10, 4),
    perc_ocup_2 int,
    vol_agendado VARCHAR(25),
    entregas int,
    pedidos int,
    d_size_agend decimal(10, 2),
    d_size_total decimal(10, 2),
    primary key (cod_cliente, mapa)
  );

CREATE TABLE -- Mensal / chave primaria definida
  IF NOT EXISTS `03_05_30_cod_ajudante` (
    cod_ajudante int,
    descricao VARCHAR(25),
    data date,
    mapa int,
    veiculo int,
    placa VARCHAR(25),
    motorista int,
    cod_produto INT,
    descricao_2 VARCHAR(25),
    cod_cliente int,
    descricao_3 VARCHAR(25),
    peso int,
    perc_ocup int,
    volume decimal(10, 4),
    perc_ocup_2 int,
    vol_agendado VARCHAR(25),
    entregas int,
    pedidos int,
    d_size_agend decimal(10, 2),
    d_size_total decimal(10, 2),
    primary key (cod_ajudante, data, mapa)
  );

CREATE TABLE -- Mensal / chave primaria definida
  IF NOT EXISTS `03_05_30_cod_motorista` (
    cod_motorista int,
    descricao VARCHAR(25),
    data date,
    mapa int,
    veiculo int,
    placa VARCHAR(25),
    motorista int,
    cod_produto int,
    descricao_2 VARCHAR(25),
    cod_cliente int,
    descricao_3 VARCHAR(25),
    peso int,
    perc_ocup int,
    volume decimal(10, 4),
    perc_ocup_2 int,
    vol_agendado VARCHAR(25),
    entregas int,
    pedidos int,
    d_size_agend decimal(10, 2),
    d_size_total decimal(10, 2),
    primary key (cod_motorista, data, mapa)
  );

CREATE TABLE -- Mensal / chave primaria definida
  IF NOT EXISTS `03_05_30_mapa` (
    mapa int,
    data date,
    mapa_2 int,
    veiculo int,
    placa VARCHAR(25),
    motorista int,
    cod_produto INT,
    descricao VARCHAR(25),
    cod_cliente int,
    descricao_2 VARCHAR(25),
    peso int,
    perc_ocup int,
    volume decimal(10, 4),
    perc_ocup_2 int,
    vol_agendado VARCHAR(25),
    entregas int,
    pedidos int,
    d_size_agend decimal(10, 2),
    d_size_total decimal(10, 2),
    primary key (mapa, data)
  );

CREATE TABLE -- Mensal / chave primaria definida
  IF NOT EXISTS `03_08_05` (
    data DATE,
    transp int,
    entrega VARCHAR(20),
    carga_atual VARCHAR(20),
    frota VARCHAR(20),
    custo_spot DECIMAL(15, 2),
    regiao int,
    veiculo int,
    placa VARCHAR(10),
    mapa INT,
    capac INT,
    entregas INT,
    cx_carreg DECIMAL(10, 2),
    cx_entreg DECIMAL(10, 2),
    ocup DECIMAL(6, 2),
    cx_rota decimal(10, 2),
    cx_as decimal(10, 2),
    veic_bm DECIMAL(6, 2),
    rshow int,
    entr_vol VARCHAR(20),
    hr_sai TIME,
    hr_entr TIME,
    km_sai INT,
    km_entr INT,
    km_prev DECIMAL(8, 2),
    tempo_prev TIME,
    vl_pto_mot DECIMAL(10, 6),
    vl_pto_ajd DECIMAL(10, 6),
    vl_eq_mot DECIMAL(10, 2),
    vl_eq_ajd DECIMAL(10, 2),
    cd_mot INT,
    cd_aju1 INT,
    cd_aju2 INT,
    km_desloc INT,
    km_laco INT,
    tmpo_desloc TIME,
    tmpo_laco TIME,
    tmpo_interno TIME,
    mot_nao_carr int,
    cx_carr_com DECIMAL(10, 2),
    capacidade_veiculo_kg DECIMAL(10, 2),
    peso_carga_kg DECIMAL(10, 2),
    classificacao_roadshow VARCHAR(20),
    classificacao_roads VARCHAR(20),
    primary key (mapa)
  );

CREATE TABLE -- Mensal / chave primaria definida
  IF NOT EXISTS `03_11_29` (
    data date,
    mapa int,
    placa VARCHAR(25),
    regiao_entrega VARCHAR(25),
    superv_rota int,
    nome_superv_rota VARCHAR(25),
    motorista int,
    nome_motorista VARCHAR(25),
    ajudante_1 int,
    nome_ajudante_1 VARCHAR(25),
    ajudante_2 int,
    nome_ajudante_2 VARCHAR(25),
    primary key (mapa)
  );

CREATE TABLE -- Mensal / chave primaria definida
  IF NOT EXISTS `03_11_40` (
    mapa INT primary key,
    veiculo INT,
    placa VARCHAR(20),
    dt_entrega DATE,
    entregas INT,
    hora_emis TIME(0),
    hora_carreg TIME(0),
    hora_saida TIME(0),
    hora_chegada TIME(0),
    hora_p_fis TIME(0),
    hora_p_fin TIME(0),
    tempo_rota TIME(2),
    tempo_p_fis TIME(2),
    tempo_p_fin TIME(2),
    tempo_interno TIME(2),
    km_inicial INT,
    km_final INT,
    km_rodado INT

  );

CREATE TABLE -- Mensal / chave primaria definida
  IF NOT EXISTS `03_18_05` (
    unb int,
    descricao_unb VARCHAR(25),
    codigo_cliente int,
    nome_cliente VARCHAR(25),
    solicitacao_reposicao int,
    tipo_solicitacao VARCHAR(25),
    data_solicitacao Varchar(25),
    hora time,
    status_solicitacao VARCHAR(25),
    data_acao date,
    usuario_acao VARCHAR(25),
    mapa_reposicao bigint,
    nota_fiscal_serie VARCHAR(25),
    status_nf VARCHAR(10),
    produto int,
    descricao_produto VARCHAR(25),
    quantidade decimal(10, 4),
    u_m VARCHAR(10),
    valor_unitario decimal(10, 2),
    valor decimal(10, 2),
    pallet VARCHAR(25),
    montagem_pallet VARCHAR(10),
    justificativa VARCHAR(10),
    mapa_origem int,
    nf_origem VARCHAR(25),
    produto_origem int,
    descricao_produto_2 VARCHAR(25),
    quantidade_origem int,
    u_m_2 VARCHAR(10),
    veiculo int,
    placa VARCHAR(25),
    transportadora int,
    nome_transportadora VARCHAR(25),
    motorista int,
    nome_motorista VARCHAR(25),
    ajudante int,
    nome_ajudante_entrega VARCHAR(25),
    ajudante_2 int,
    nome_ajudante_entrega_2 VARCHAR(25),
    conferente_solicitacao_reposicao VARCHAR(25),
    nome_conferente_solicitacao_reposicao VARCHAR(25),
    conferente_carregamento VARCHAR(25),
    nome_conferente_carregamento VARCHAR(25),
    ajudante_carregamento VARCHAR(25),
    nome_ajudante_carregamento VARCHAR(25),
    ajudante_carregamento_2 VARCHAR(25),
    nome_ajudante_carregamento_2 VARCHAR(25),
    ajudante_carregamento_3 VARCHAR(25),
    nome_ajudante_carregamento_3 VARCHAR(25),
    ajudante_carregamento_4 VARCHAR(25),
    nome_ajudante_carregamento_4 VARCHAR(25),
    ajudante_carregamento_5 VARCHAR(25),
    nome_ajudante_carregamento_5 VARCHAR(25),
    ajudante_carregamento_6 VARCHAR(25),
    nome_ajudante_carregamento_6 VARCHAR(25),
    origem_blitz_carreg VARCHAR(25),
    nr_pedido_reposicao int,
    unb_cliente int,
    opcao_de_reposicao VARCHAR(25),
    status_check_reposicao VARCHAR(25),
    usuario_acao_check VARCHAR(25),
    data_acao_check varchar(25),
    sistema_origem VARCHAR(25),
    observacao VARCHAR(100),
    perfil_aprovacao_automatica VARCHAR(25),
    data_revisao varchar(25),
    usuario_revisao VARCHAR(25),
    tipo_cliente VARCHAR(25),
    setor_venda int,
    unnamed_69 VARCHAR(25),
    primary key (solicitacao_reposicao, produto)
  ) ROW_FORMAT = DYNAMIC;

CREATE TABLE -- Mensal / chave primaria definida
  IF NOT EXISTS aderencia_tracking_mes (
    classe varchar(25),
    data date,
    mapa int,
    placa varchar(10),
    cod_cliente int,
    seq_real int,
    seq_plan int,
    inicio_rota DATETIME,
    horario_matinal DATETIME,
    saida_cdd datetime,
    chegada_ao_pdv datetime,
    tempo_prev_retorno time,
    tempo_retorno time,
    dist_prev_retorno decimal(10, 4),
    dist_perc_retorno decimal(10, 3),
    inicio_entrega DATETIME,
    fim_entrega DATETIME,
    fim_rota DATETIME,
    entrada_cdd DATETIME,
    caixas_carregadas DECIMAL(10, 2),
    caixas_devolvidas decimal(10, 2),
    repasse int,
    tempo_de_entrega time,
    tempo_descarga time,
    tempo_espera time,
    tempo_almoco time,
    tempo_total_de_rota time,
    disp_apont_cadastrado decimal(10, 3),
    lat_entrega decimal(10, 7),
    lon_entrega decimal(10, 7),
    unidade_negocio int,
    transportadora varchar(50),
    lat_cliente_apontamento decimal(10, 7),
    lon_cliente_apontamento decimal(10, 7),
    lat_atual_cliente decimal(10, 7),
    lon_atual_cliente decimal(10, 7),
    distancia_prev decimal(10, 3),
    tempo_deslocamento TIME,
    vel_media_km_h int,
    distancia_perc_apontamento decimal(10, 3),
    aderencia_sequencia_entrega varchar(10),
    aderencia_janela_entrega varchar(10),
    pdv_lacrado varchar(10),
    codigo_transportadora int,
    hodometro_ao_sair_do_deposito int,
    hodometro_ao_voltar_ao_deposito int,
    acessou_raio_pdv varchar(10),
    freteiro varchar(10),
    segmento varchar(10),
    avaliacao_do_pdv int,
    observacao_da_avaliacao_do_pdv varchar(50),
    hodometro_no_carregamento int,
    aderente_foxtrot varchar(50),
    horario_previsto_chegada datetime,
    horario_previsto_saida DATETIME,
    tempo_previsto TIME,
    distancia_prevista decimal(10, 3),
    ocorrencia varchar(25),
    saida_do_raio datetime,
    tempo_no_pdv time,
    grupo_de_clientes varchar(25),
    geo varchar(25),
    frota varchar(25),
    data_fim_entrega datetime,
    partida_prevista_deposito datetime,
    numero_roadshow varchar(25),
    sequencia_sugerida int,
    seq_real_click int,
    primary key (mapa, cod_cliente, sequencia_sugerida)
  );

CREATE TABLE -- Cadastro / chave primaria definida
  IF NOT EXISTS ajudante (
    codigo INT,
    nome_ajudante VARCHAR(100),
    cpf VARCHAR(20),
    supervisor_rota int,
    status VARCHAR(25),
    primary key (codigo)
  );

  CREATE TABLE -- Mensal / chave primaria definida
    IF NOT EXISTS base_rating (
      data_da_avaliacao date,
      avaliacao int,
      classificacao VARCHAR(25),
      cod_cdd bigint,
      motorista VARCHAR(25),
      cod_pdv int,
      nome_pdv VARCHAR(25),
      transportadora VARCHAR(25),
      mapa int,
      pedido int,
      motivo VARCHAR(100),
      comentario text,
      estado VARCHAR(25),
      cidade VARCHAR(25),
      primary key (data_da_avaliacao, avaliacao, cod_pdv)
    );

CREATE TABLE -- Mensal / chave primaria definida
  IF NOT EXISTS bees_deliver_dia (
    tour_display_id bigint,
    tour_date date,
    distribution_center_id int,
    driver_name VARCHAR(25),
    truck_license_plate varchar(10),
    poc_external_id int,
    poc_name varchar(25),
    critical_poc varchar(10),
    status VARCHAR(25),
    trip_start_timestamp datetime (3),
    trip_end_timestamp datetime (3),
    original_order int,
    order_updated int,
    visit_order int,
    delivery_window varchar(25),
    within_radius VARCHAR(25),
    skipped_reason varchar(10),
    out_of_radius_reason varchar(100),
    actual_delivery_time int,
    driver_notification_time datetime (3),
    arrived_at datetime (3),
    finished_at datetime (3),
    last_reason_waiting_modulation VARCHAR(25),
    last_reason_rescheduled VARCHAR(25),
    devolution_waiting_modulation varchar(25),
    return_waiting_modulation_time int,
    return_in_treatment_time int,
    poc_rescheduled_count int,
    count_of_time_dispersion_alert int,
    last_time_dispersion_handled varchar(25),
    last_time_dispersion_reason varchar(25),
    total_visit_delay_pending_time int,
    total_visit_delay_in_treatment_time int,
    total_pnp_time int,
    total_financial_settlement_time varchar(25),
    total_inventory_settlement_time varchar(25),
    total_delivered_vol VARCHAR(25),
    total_refused_vol VARCHAR(25),
    foxtrot_adherence VARCHAR(25),
    estimated_delivery_time int,
    volume_hectoliters_sum VARCHAR(25),
    bees_poc_id bigint,
    bees_tour_id VARCHAR(25),
    bees_trip_id VARCHAR(25),
    bees_created_date DATETIME (3),
    bees_last_reason_id_waiting_modulation VARCHAR(25),
    bees_last_reason_id_waiting_rescheduled VARCHAR(25),
    primary key (tour_date, poc_external_id)
  ) ROW_FORMAT = DYNAMIC;

CREATE TABLE -- Mensal / UNIQUE KEY Definida
  IF NOT EXISTS bees_deliver_mes_antigo (
    arrived_at DATETIME,
    assistants_quantity int,
    chave_mapa varchar(25),
    cod_cliente int,
    driver_external_id varchar(25),
    estimated_time_arrival DATETIME,
    estimated_time_departure datetime,
    finished_at datetime,
    last_reason_rescheduled varchar(50),
    last_reason_waiting_modulation varchar(50),
    last_timestamp_on_the_way varchar(50),
    last_timestamp_rescheduled datetime,
    soma_de_optimized_order int,
    soma_de_original_order int,
    poc_external_id int,
    soma_de_poc_latitude decimal(9, 6),
    soma_de_poc_longitude decimal(9, 6),
    poc_name varchar(50),
    status varchar(25),
    total_delivered_value int,
    total_delivered_vol varchar(50),
    total_refused_value int,
    total_refused_vol varchar(50),
    total_value int,
    total_weight_kg int,
    tour_date date,
    tour_display_id int,
    tour_display_id_original int,
    contagem_de_tour_trip_id int,
    soma_de_trip_display_id int,
    trip_end_timestamp datetime,
    trip_start_timestamp datetime,
    vehicle_license_plate varchar(10),
    visit_order int,
    volume_hectoliters_sum int,
    volume_packages int,
    within_radius varchar(10),
    diff_departure_arrival int,
    diff_finished_arrived int,
    foxtrot_adherence varchar(10),
    UNIQUE KEY bees_deliver_mes_antigo_trip_unique (
      tour_display_id,
      poc_external_id,
      trip_start_timestamp
    )
  ) ROW_FORMAT = DYNAMIC;

CREATE TABLE -- Mensal /
  IF NOT EXISTS bees_deliver_mes_novo (
    chegou_em datetime,
    quantidade_de_assistentes int,
    chave_mapa varchar(25),
    cod_cliente int,
    nome_cliente varchar(100),
    id_motorista varchar(25),
    hora_estimada_chegada datetime,
    hora_estimada_partida datetime,
    finalizada_em datetime,
    ultimo_motivo_reagendamento varchar(25),
    ultimo_motivo_tratamento_cme varchar(25),
    ultimo_carimbo_de_data_no_caminho datetime,
    ultimo_carimbo_de_data_remarcado datetime,
    pedido_otimizado int,
    pedido_original int,
    latitude_prevista decimal(9, 6),
    longitude_prevista decimal(9, 6),
    latitude_real decimal(9, 6),
    longitude_real decimal(9, 6),
    dif_distancia_km decimal(10, 2),
    status varchar(25),
    valor_total_entregue decimal(10, 2),
    vol_total_entregue varchar(50),
    valor_total_recusado decimal(10, 2),
    vol_total_recusado varchar(50),
    valor_total decimal(10, 2),
    peso_total_kg varchar(50),
    tour_date date,
    tour_display_id int,
    tour_display_id_original int,
    contagem_de_trip_display_id int,
    trip_display_id int,
    carimbo_de_data_final_da_viagem datetime,
    carimbo_de_data_inicio_da_viagem datetime,
    placa varchar(10),
    ordem_visita int,
    sum_vol_hectolitro varchar(50),
    vol_caixas varchar(50),
    dentro_do_raio varchar(10),
    dif_partida_chegada int,
    dif_finalizado_chegada int,
    aderencia_ao_foxtrot varchar(10),
    comentarios_monitoramento varchar(200),
    vehicle_external_id varchar(25),
    cod_revenda varchar(25)
  ) ROW_FORMAT = DYNAMIC;

CREATE TABLE -- Cadastro / chave primaria definida
  IF NOT EXISTS expurgos (mapa INT primary key);

CREATE TABLE -- Mensal / chave primaria definida
  IF NOT EXISTS jornada_laboral (
    data date,
    funcionario VARCHAR(25),
    matricula int,
    e time,
    sa time,
    ra time,
    s time,
    trabalhadas time,
    primary key (data, matricula)
  );

CREATE TABLE -- Cadastro / chave primaria definida
  IF NOT EXISTS motoristas (
    cod_filial int,
    descricao_filial VARCHAR(25),
    cod_motorista int,
    nome_motorista VARCHAR(25),
    status VARCHAR(25),
    cod_supervisor_rota int,
    cpf VARCHAR(25),
    data_admissao varchar(25),
    data_inativacao VARCHAR(25),
    j_alternativa int,
    descricao_j_alternativa varchar(25),
    rota_gradativa VARCHAR(10),
    celular_corporativo VARCHAR(25),
    cod_cluster int,
    cluster VARCHAR(25),
    primary key (cod_motorista)
  );

CREATE TABLE -- Mensal / chave primaria definida
  IF NOT EXISTS `relatorio_separacao_wms` (
    codigo_do_armazem int,
    mapa int,
    palete VARCHAR(25),
    data_de_entrega date,
    inicio_palete datetime,
    fim_palete datetime,
    esforco int,
    usuario_finalizou_palete varchar(25),
    finalizado_cfe_indicacao_tc varchar(2 5),
    endereco_destino varchar(25),
    peso_do_palete_ok varchar(10),
    peso_palete_esperado varchar(25),
    peso_palete_real varchar(25),
    balanca varchar(25),
    codigo_do_item int,
    descricao_do_item varchar(60),
    tipo varchar(25),
    peso_item_esperado decimal(10, 2),
    peso_item_real varchar(25),
    enderecos_sugeridos varchar(25),
    endereco_selecionado varchar(25),
    quantidade int,
    unidade_de_medida varchar(25),
    chapatex varchar(25),
    papelao varchar(25),
    sequencia int,
    usuario_separacao varchar(25),
    inicio_separacao_item datetime,
    fim_separacao_item datetime,
    esforco_item int,
    peso_do_item_ok varchar(25),
    item_conferido varchar(10),
    ultima_ocorrencia varchar(25),
    palete_conferido varchar(25),
    palete_iniciou_com_produto varchar(25),
    sorteado_para_blitz varchar(25),
    regras_de_blitz_classificadas varchar(50),
    utilizou_percentual_minimo varchar(25),
    status_do_palete varchar(25),
    conferencia_obrigatoria varchar(25),
    identificacao_da_caixa varchar(25),
    peso_dos_ativos varchar(25),
    unique key relatorio_separacao_wms_unique_key (
      mapa,
      codigo_do_item,
      sequencia,
      quantidade,
      usuario_finalizou_palete,
      identificacao_da_caixa,
      esforco_item
    )
  );

CREATE TABLE -- Cadastro / chave primaria definida
  IF NOT EXISTS veiculos (
    frota INT,
    operacao varchar(25),
    tipo_de_bem varchar(25),
    carroceria varchar(25),
    marca_bau varchar(25),
    fabricante varchar(25),
    marca_mod varchar(25),
    ano_fabric int,
    placa varchar(10),
    primary key (frota, operacao)
  );

-- log
CREATE TABLE
  IF NOT EXISTS log_ingestao (
    id INT AUTO_INCREMENT PRIMARY KEY,
    tabela_destino VARCHAR(50) NOT NULL, -- Ex: "03_11_40"
    nome_arquivo VARCHAR(50) NOT NULL, -- Ex: "janeiro.csv"
    ano INT NOT NULL, -- Ex: 2025
    mes varchar(25),
    dia int,
    coluna_data varchar(25),
    data_upload DATETIME NOT NULL, -- Ex: NOW()
    hash_arquivo CHAR(64) NOT NULL, -- SHA-256 hash
    sucesso BOOLEAN NOT NULL, -- true / false
    mensagem_erro TEXT -- null ou texto com o erro
  )


  CREATE TABLE 
    IF NOT EXISTS qlp(
      data date,
      matinal time,
      ff int,
      tipo varchar(10),
      cdm int,
      motorista varchar(25),
      cda int,
      ajudante varchar(25),
      cda2 int,
      ajudante2 varchar(25),
      disponibilidade varchar(25),
      fixa varchar(10),
      alternativa varchar(10),
      peso int,
      entregas int,

      primary key(ff, tipo),
      unique key(ff, tipo, motorista)

    )